### ISSUE TITLE
feature request : matte choker 

### ISSUE THREAD

**Issue by Ulf3000** [chsh2/texture_vfx_control#1]
hey man , you again show prowess and deliver. 
great addon , the chromakey works great .. can you modify it to make a simple matte choker ? i sometimes have white lines around alpha textures, and its hard to get by with blender`s  native tools. 

i would modify it myself if i knew wtf is going on lol , but the math is a bit complicated for me. Would be great to have , 

thanx for listening

**Comment by Ulf3000** [comment]
edit: i now just experimented - and it seems a simple maprange node on the alpha channel does the trick already... have to try with more textures though.. dial the to min value down .. but only works if no other color processing nodes are present.. these seems to clamp the values to 0-255 while the alpha channel is processed as 32bit internally otherwise

**Comment by chsh2** [comment]
Hello. I am a bit surprised that you have tried this add-on, since I have not announced this project in social media. (I got some real-life troubles recently and have to slow down the add-on development.) Anyway, thanks for your feedback!

I think the "Simple Choker" function in After Effects removes some pixels from the contour. Maybe I can modify the Outline node group of this add-on to achieve this effect. The following video is my current test result:

https://github.com/chsh2/texture_vfx_control/assets/110356534/2d3d7d0a-2442-4d93-892d-54244c7cb5d7

However, for the other function "Matte Choker" in After Effects (filling transparent holes), I do not think it can be implemented as a shader.

**Comment by Ulf3000** [comment]
yeah im subsribed and if i search somethnhing for blender i go to github first most of the time , there are so many unannounced great addons/scripts on github. But this can be closed, simple math functions like maprange or smooth minimum do the trick already.

**Comment by chsh2** [comment]
OK I will close the issue for now. I will also add the outline-based choker in the next release.
